### ISSUE TITLE
"rnpm" config that will stop working from next react-native

### ISSUE THREAD

**Issue by Ahmed-Soudi** [Pushwoosh/pushwoosh-geozones-react-native-plugin#3]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - pushwoosh-geozones-react-native-plugin: https://github.com/Pushwoosh/pushwoosh-geozones-react-native-plugin#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by wfhm** [comment]
Hello @AhmedPro2013,

Checking it.

**Comment by wfhm** [comment]
@AhmedPro2013,

The new plugin version is released in npm, please try updating it.
